services:
  - docker
env:
  matrix:
    - DOCKER_IMAGE=esd-circle-bot
language: node_js
node_js:
  - "7"
install:
  - npm install

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh